// web/src/pages/Notifications/Notifications.vue
<script setup lang="ts">
import { BellIcon } from "lucide-vue-next";
import { Button } from "@/components/ui/button";
import Layout from "../../components/Layout.vue";
import CreateNotifications from "@/components/CreateNotifications.vue";
</script>

<template>
  <Layout>
    <div
      class="w-full border rounded p-2 md:p-8 flex flex-col gap-10 col-span-full"
    >
      <div class="col-span-full flex items-start justify-between">
        <div class="flex w-full flex-col gap-1">
          <h1 class="font-cal text-xl md:text-3xl">Notifications</h1>
          <p class="text-muted-foreground">
            Overview of all your notification channels.
          </p>
        </div>
        <CreateNotifications>
          <Button>Create</Button>
        </CreateNotifications>
      </div>
      <div class="flex flex-col gap-1 items-center border rounded-sm py-16">
        <BellIcon class="mb-2 text-muted-foreground" />
        <p>No notifications</p>
        <p class="mb-2">Create your first notification channel</p>
        <CreateNotifications>
          <Button>Create</Button>
        </CreateNotifications>
      </div>
    </div>
  </Layout>
</template>

// apps/web/app/(app)/notifications/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { fetchNotifications } from "@/lib/api/notifications";
import DataTable from "@/components/notifications/data-table";
import EmptyState from "@/components/empty-state";
import { BellDotIcon } from "lucide-react";

export const metadata: Metadata = {
  title: "Notifications | Upstat",
  description: "Simple & easy status monitoring.",
};

export default async function Notifications() {
  const notifications = await fetchNotifications();

  return (
    <div className="flex flex-col w-full gap-8">
      <div className="flex items-end justify-between ">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-bold">Notifications</h1>
          <p className="text-muted-foreground">
            Overview of all your notification channels.
          </p>
        </div>

        <Button asChild>
          <Link href="/notifications/create">Create</Link>
        </Button>
      </div>

      {!notifications?.notifications ? (
        <EmptyState
          icon={<BellDotIcon />}
          title="No notifications channels"
          description="Create your first notification channel"
          action={
            <Button className="mt-4" asChild>
              <Link href="/notifications/create">Create</Link>
            </Button>
          }
        />
      ) : (
        <DataTable data={notifications?.notifications} />
      )}
    </div>
  );
}
