// web/src/pages/Notifications/Notifications.vue
<script setup lang="ts">
import { BellIcon } from "lucide-vue-next";
import { Button } from "@/components/ui/button";
import Layout from "../../components/Layout.vue";
import CreateNotifications from "@/components/CreateNotifications.vue";
</script>

<template>
  <Layout>
    <div
      class="w-full border rounded p-2 md:p-8 flex flex-col gap-10 col-span-full"
    >
      <div class="col-span-full flex items-start justify-between">
        <div class="flex w-full flex-col gap-1">
          <h1 class="font-cal text-xl md:text-3xl">Notifications</h1>
          <p class="text-muted-foreground">
            Overview of all your notification channels.
          </p>
        </div>
        <CreateNotifications>
          <Button>Create</Button>
        </CreateNotifications>
      </div>
      <div class="flex flex-col gap-1 items-center border rounded-sm py-16">
        <BellIcon class="mb-2 text-muted-foreground" />
        <p>No notifications</p>
        <p class="mb-2">Create your first notification channel</p>
        <CreateNotifications>
          <Button>Create</Button>
        </CreateNotifications>
      </div>
    </div>
  </Layout>
</template>

// web/src/pages/Notifications/index.tsx
import DashboardLayout from "@/components/DashboardLayout";
import { Helmet } from "react-helmet-async";
import RedirectOnNoUser from "@/components/RedirectOnNoUser";
import { BellDotIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";

export default function index() {
  return (
    <RedirectOnNoUser>
      <div className="m-auto max-w-[1200px] flex flex-col gap-4">
        <Helmet>
          <title>Notifications | Upstat</title>
        </Helmet>
        <DashboardLayout>
          <div className="flex flex-col w-full gap-8">
            <div className="flex flex-col gap-1">
              <h1 className="text-2xl font-bold">Notifications</h1>
              <p className="text-muted-foreground">
                Overview of all your notification channels.
              </p>
            </div>

            <div className="flex flex-col items-center py-4 border">
              <BellDotIcon />
              <h3>No notifications channels</h3>
              <p className="text-muted-foreground">
                Create your first notification channel
              </p>
              <Button className="mt-4" asChild>
                <Link to="/app/notifications/create">Create</Link>
              </Button>
            </div>
          </div>
        </DashboardLayout>
      </div>
    </RedirectOnNoUser>
  );
}
